### ISSUE TITLE
Typora 支持 PicGo 来上传图片了 | MARKSZのBlog

### ISSUE THREAD

**Issue by Molunerfinn** [Molunerfinn/Molunerfinn.github.io#111]
https://molunerfinn.com/typora-supports-picgo/#%E5%B0%8F%E7%BB%93 

 Typora 支持 PicGo 来上传图片了

**Comment by FuShaoLei** [comment]
太强了👍

**Comment by SnowySound** [comment]
刚刚发现PicGo跟主题都是作者写的，太优秀了！！！

**Comment by chenluby** [comment]
环境window，本地PicGo版本为2.2.2，typora0.9.8.6选择PicGo(app)验证图片上传选项时自动进入到PicGo无任何反应，当返回typora时提示Failed to fetch。日志只有[PicGo INFO] [PicGo Server] is listening at 36683。在typora上传服务设定-上传服务未设置None时，PicGo为上传失败，日志提示2020-03-14 01:31:45 [PicGo INFO] Before transform
2020-03-14 01:31:45 [PicGo INFO] Transforming...
2020-03-14 01:31:45 [PicGo INFO] Before upload
2020-03-14 01:31:45 [PicGo INFO] Uploading...
2020-03-14 01:31:47 [PicGo WARN] failed
2020-03-14 01:31:47 [PicGo ERROR] StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
    at new StatusCodeError (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End-------

**Comment by chenluby** [comment]
经测试typora上传服务设定-上传服务设置回None时，PicGo还是上传失败，当关闭Typora后PicGo上传正常

**Comment by Molunerfinn** [comment]
> 环境window，本地PicGo版本为2.2.2，typora0.9.8.6选择PicGo(app)验证图片上传选项时自动进入到PicGo无任何反应，当返回typora时提示Failed to fetch。日志只有[PicGo INFO] [PicGo Server] is listening at 36683。在typora上传服务设定-上传服务未设置None时，PicGo为上传失败，日志提示2020-03-14 01:31:45 [PicGo INFO] Before transform
> 2020-03-14 01:31:45 [PicGo INFO] Transforming...
> 2020-03-14 01:31:45 [PicGo INFO] Before upload
> 2020-03-14 01:31:45 [PicGo INFO] Uploading...
> 2020-03-14 01:31:47 [PicGo WARN] failed
> 2020-03-14 01:31:47 [PicGo ERROR] StatusCodeError: 422 - {"message":"Invalid request.\n\n"sha" wasn't supplied.","documentation_url":"[https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}](https://developer.github.com/v3/repos/contents/#create-or-update-a-file%22%7D)
> ------Error Stack Begin------
> StatusCodeError: 422 - {"message":"Invalid request.\n\n"sha" wasn't supplied.","documentation_url":"[https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}](https://developer.github.com/v3/repos/contents/#create-or-update-a-file%22%7D)
> at new StatusCodeError (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
> at Request.plumbing.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
> at Request.RP$callback [as _callback] (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
> at Request.self.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
> at Request.emit (events.js:200:13)
> at Request. (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
> at Request.emit (events.js:200:13)
> at IncomingMessage. (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
> at Object.onceWrapper (events.js:288:20)
> at IncomingMessage.emit (events.js:205:15)
> -------Error Stack End-------

这是因为你已经在github上传过同名文件了…PicGo目前不支持github上传同名文件。这恰恰说明上传功能是好的。

**Comment by chenluby** [comment]
> @Molunerfinn
> > 环境window，本地PicGo版本为2.2.2，typora0.9.8.6选择PicGo(app)验证图片上传选项时自动进入到PicGo无任何反应，当返回typora时提示Failed to fetch。日志只有[PicGo INFO] [PicGo Server] is listening at 36683。在typora上传服务设定-上传服务未设置None时，PicGo为上传失败，日志提示2020-03-14 01:31:45 [PicGo INFO] Before transform
> > 2020-03-14 01:31:45 [PicGo INFO] Transforming...
> > 2020-03-14 01:31:45 [PicGo INFO] Before upload
> > 2020-03-14 01:31:45 [PicGo INFO] Uploading...
> > 2020-03-14 01:31:47 [PicGo WARN] failed
> > 2020-03-14 01:31:47 [PicGo ERROR] StatusCodeError: 422 - {"message":"Invalid request.\n\n"sha" wasn't supplied.","documentation_url":"[https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}](https://developer.github.com/v3/repos/contents/#create-or-update-a-file%22%7D)
> > ------Error Stack Begin------
> > StatusCodeError: 422 - {"message":"Invalid request.\n\n"sha" wasn't supplied.","documentation_url":"[https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}](https://developer.github.com/v3/repos/contents/#create-or-update-a-file%22%7D)
> > at new StatusCodeError (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:32:15)
> > at Request.plumbing.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:104:33)
> > at Request.RP$callback [as _callback] (D:\SoftWare\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
> > at Request.self.callback (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
> > at Request.emit (events.js:200:13)
> > at Request. (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1161:10)
> > at Request.emit (events.js:200:13)
> > at IncomingMessage. (D:\SoftWare\PicGo\resources\app.asar\node_modules\request\request.js:1083:12)
> > at Object.onceWrapper (events.js:288:20)
> > at IncomingMessage.emit (events.js:205:15)
> > -------Error Stack End-------
> 
> 这是因为你已经在github上传过同名文件了…PicGo目前不支持github上传同名文件。这恰恰说明上传功能是好的。而且请注意看文章里的说明，PicGo Server的端口需要是36677，你看看你的端口根本就不对，好好看看文档吧

https://cdn.jsdelivr.net/gh/chenluby/imageCDN/upload/demo.png
教程没说设置端口啊，我用 的默认的。至于同名问题，我复制了几个副本只要typora的图像那里当从picGo(app)设置回来none，如果没关闭typora。PicGo也没法上传报上面的错，当设置回来none“重启”后typora没关闭PicGo能正常上传。不知道是我环境问题还是typora兼容问题，也重装过了
